spring:
 datasource:
   url: jdbc:mysql://localhost:3306/coffee1
   username: root
   password: admin123
   driver-class-name: com.mysql.cj.jdbc.Driver


jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

